name: Imjjong
title: Imjjong's works log
description: made by jjong
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Tips
    url: /Tips
  - title: Feed
    url: /feed.xml
email: lvzerovl@naver.com
disqus_username: disqus_username
